// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"

	"github.com/QEasyWeb3/QEasyChain/common"
)

var _ = (*initMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (i Init) MarshalJSON() ([]byte, error) {
	type Init struct {
		Admin common.Address `json:"admin,omitempty"`
	}
	var enc Init
	enc.Admin = i.Admin
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (i *Init) UnmarshalJSON(input []byte) error {
	type Init struct {
		Admin *common.Address `json:"admin,omitempty"`
	}
	var dec Init
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Admin != nil {
		i.Admin = *dec.Admin
	}
	return nil
}
